language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"

# command to install dependencies
install:
  - "pip install lxml"  
  - "pip install . --use-mirrors"


script:  
  - cd ./lems/test && nosetests -vs

